flights/flights/urls.py
from django.contrib import admin
from django.urls import path,include
from fly.views import Home
from fly.views import FlightList, FlightDetail
from .  import views
from fly import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name="home"),
    path("list/", FlightList.as_view(), name="list" ),
    path('detail/<int:pk>', FlightDetail.as_view(), name="detail" ),
    path("register/", views.User_register, name="register" ),
    path("login/", views.User_login, name="login"),
    path("logout/", views.User_logout, name="logout"),
    path("fly/", include('fly.urls'))


]

flights/fly/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path("search/", views.search, name= "search"),
    path("category/<int:pk>",views.CategoryDetailView.as_view(),name="category"),
    path("payment/<int:planeId>", views.payment, name="payment"),
    path("book/<str:TicketNo>", views.book, name="book")
]

flights/fly/models.py
from django.db import models

# Create your models here.

class category(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return f"{self.name}"


class fly(models.Model):
    Flight_Name = models.CharField(max_length =100, default="None")
    From = models.CharField(max_length =100, default="None")
    To = models.CharField(max_length=100, default="None")
    Date = models.DateField(default=None)
    Price = models.PositiveIntegerField()
    Duration= models.CharField(max_length=100, default="1 Hour")
    category = models.ForeignKey(category, on_delete = models.PROTECT,null=True)

class Ticket(models.Model):
    TicketNo = models.PositiveIntegerField()
    Name = models.CharField(max_length = 100, default= "None")
    Flight_Name = models.CharField(max_length = 100, default= "None")
    From = models.CharField(max_length = 100, default= "None")
    To = models.CharField(max_length = 100, default= "None")

class Passenger(models.Model):
    Name = models.CharField(max_length=100)
    Age = models.PositiveIntegerField()
    Gender = models.CharField(max_length = 100)
    fly_id = models.ForeignKey(fly, on_delete = models.CASCADE)

    




    
    

    

flights/flights/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

flights/flights/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, HttpResponseRedirect
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate,login,logout






def User_register(request):

    if request.method == "GET":
        form = CustomUserCreationForm()

    if request.method == "POST":
        form = CustomUSerCreationForm(request.POST)
        if form.is_valid():
          form.save()
    
    return render(request,"register.html", {"form":form})

def User_login(request):
    if request.method == "GET":
        return render(request, "login.html")

    if request.method=="POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

    user = authenticate(username = username, password= password)

    if user is not None:
        login(request,user)
        return HttpResponseRedirect("/")


def User_logout(request):
    logout(request)
    return HttpResponseRedirect("/login")

flights/fly/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import fly,category, Ticket, Passenger
from django.db.models import Q
import razorpay
import random
from django.views.decorators.csrf import csrf_exempt




# Create your views here.


def Home(request):
    return render(request,"index.html")


class FlightList(ListView):
    model = fly
    context_object_name = "list"


class FlightDetail(DetailView):
    model = fly
    context_object_name = "detail"
    template_name = "fly/fly_detail.html"


def search(request):
    from_ = request.GET.get("from")
    to = request.GET.get("to")
    date = request.GET.get("date")

    flight = fly.objects.filter(Q(From = from_) & Q(To=to) )

    return render(request, "fly/search.html", {"flight": flight})

class CategoryDetailView(DetailView):
    model=category
    template_name="category/category.html"
    context_object_name="categoryob"


def payment(request,planeId):

     flyId = fly.objects.get(id = planeId)

     name = request.GET.get("name")
     age = request.GET.get("age")
     gender = request.GET.get("gender")

     passenger = Passenger.objects.create(Name =name, Age=age, Gender=gender, fly_id = flyId )

     request.session["P_id"]= passenger.id




     plane = fly.objects.get(id = planeId)
     amount = plane.Price*100

     TicketNo = str(random.randint(21212,937237)*planeId)
     print(TicketNo)


     client=razorpay.Client(auth=("rzp_test_tXhb7aXiGBGPzD","9tr12zxl6DeyAEAQdkHAGShJ"))
     data={"amount": amount,"currency":"INR","receipt": TicketNo}
     payment=client.order.create(data=data)
     print(payment)
     return render(request,"fly/payment.html",{"payment":payment, "TicketNo":TicketNo})


@csrf_exempt
def book(request, TicketNo):

    p = Passenger.objects.get(id = request.session.get("P_id"))
    ticket = Ticket.objects.create(TicketNo = int(TicketNo), Name = p.Name , Flight_Name = p.fly_id.Flight_Name,
    From = p.fly_id.From, To = p.fly_id.To)
    return render(request, "fly/ticket.html", {"Ticket": ticket})

flights/fly/templates/category/category.html
{% extends 'base.html'%}


{% block content%}
<div style="margin-left: 5%; margin-right: 5%;">
<table class="table table-bordered border-primary">
    <button style="border: 1px solid black;  background-color: rgb(102, 102, 221); color: white; padding: 10px;" >Domestic</button>
    <button style="border: 1px solid black;  background-color: rgb(102, 102, 221); color: white; padding: 10px;" >International</button>

    <thead>
<tr>
<th scope="col">Id</th>
<th scope="col">Flight Name</th>
<th scope="col">From</th>
<th scope="col">To</th>
<th scope="col">Date</th>
<th scope="col">Price</th>
<th scope="col">Category</th>
<th scope="col">Duration</th>
<th>Book Now</th>


</tr>
</thead>

{% for fly in categoryob.fly_set.all%}


<tr>
<td>{{fly.id}}</td>
<td>{{fly.Flight_Name}}</td>
<td>{{fly.From}}</td>
<td>{{fly.To}}</td>
<td>{{fly.Date}}</td>
<td>{{fly.Price}}</td>
<td>{{fly.category}}</td>
<td>{{fly.Duration}}</td>
<td><a class="btn btn-warning" href=" " role="button">Book ticket</a></td>

</tr>
{%endfor%}

</table>
</div>

{%endblock%}

flights/fly/templates/fly/fly_detail.html
{% extends 'base.html' %}

{% block content  %} 



<!--<div class="card" style="width: 100;">
    <div class="card-body">
      <h5 class="card-title">{{detail.Flight_Name}}</h5>
      <p class="card-text">Flight Id: {{detail.id}} </p>
      <p class="card-text">From: {{detail.From}}</p>
      <p class="card-text">To: {{detail.To}}</p>

      <a href="#" class="btn btn-primary">Book</a>
    </div>
  </div>-->

  <form action="{% url 'payment' detail.id %}">

  <div class="flight-booking">
    <h2>{{detail.From}} → {{detail.To}}</h2>
    <p><strong>Date:</strong>{{detail.Date}}</p>
    <p><strong>Airline:</strong>{{detail.Flight_Name}}</p>
    <p><Strong>Category:</Strong>{{detail.category}}</p>
    <p><strong>Duration:</strong>{{detail.Duration}}</p>
    <p><strong>Price:</strong>{{detail.Price}}</p>
    <p><strong>Arrival:</strong>{{detail.To}}</p>
    <p><strong>Baggage:</strong> Cabin - 7 Kgs (1 piece only)/Adult, Check-In - 15 Kgs/Adult</p>
    <button>+ADD Extra Check-In Baggage</button>


      <label for="">Enter Name</label>
      <input type="text" name="name"><br>
      <label for="">Enter Age</label><br>
      <input type="number" name="age" ><br>
      <label for="gender">Gender</label><br>
      Male:<input type="radio" value="male" name="gender">Female:<input type="radio" value="female" name="gender">
    

    <h3>Cancellation Refund Policy</h3>
    <ul>
      <li>₹3,450 if cancelled now</li>
      <li>₹3,975 if cancelled on May 20 at or after 12:05</li>
      <li>₹10,423 if cancelled on May 21 at or after 10:05</li>
    </ul>
  </div>

  <button class="btn btn-primary" type="submit" >Book Ticket</button> 


</form>










{%endblock%}

flights/fly/templates/fly/fly_list.html
{% extends 'base.html' %}

{% block content  %}    

<div style="margin-left: 5%; margin-right: 5%;" >
    <table class="table table-bordered border-primary">
    <h2 style="color: red; text-align: center;">Ticket & Booking</h2>
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Flight Name</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Date</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col">Duration</th>
            <th>Book Now</th>


          
            
          </tr>
        </thead>

        {% for i in list%}
        <tr>
            <td>{{i.id}}</td>
            <td>{{i.Flight_Name}}</td>
            <td>{{i.From}}</td>
            <td>{{i.To}}</td>
            <td>{{i.Date}}</td>
            <td>{{i.Price}}</td>
            <td>{{i.category.name}}</td>
            <td>{{i.Duration}}</td>
            <td><a class="btn btn-warning" href="{% url 'detail' i.id %} " role="button">Book ticket</a></td>
            
        </tr>
 
        {%endfor%}

    </table>
</div>



{%endblock%}

    

flights/fly/templates/fly/payment.html
{% extends 'base.html' %}

{% block content %}


<button id="rzp-button1" style="padding:.75rem 2rem; outline: none; border:2px solid black;font-size: 1rem; font-weight: 500;color: var(--white); background-color: var(--primary-color);border-radius: 2rem;cursor: pointer;">Pay with Razorpay</button>


<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_tXhb7aXiGBGPzD", // Enter the Key ID generated from the Dashboard
    "amount": "{{payment.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Fly Emirates",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "{% url 'book' TicketNo %}",
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>


{%endblock%}

flights/fly/templates/fly/search.html
{% extends 'base.html' %}

{% block content %}


<div>
    <table class="table table-bordered border-primary">
    <h2 style="color: red; text-align: center;">Ticket & Booking</h2>
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Flight Name</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Date</th>
            <th scope="col">Price</th>
            <th scope="col">Category</th>
            <th scope="col">Duration</th>
            <th>Book Now</th>


          
            
          </tr>
        </thead>

        {% for i in flight%}
        <tr>
            <td>{{i.id}}</td>
            <td>{{i.Flight_Name}}</td>
            <td>{{i.From}}</td>
            <td>{{i.To}}</td>
            <td>{{i.Date}}</td>
            <td>{{i.Price}}</td>
            <td>{{i.category.name}}</td>
            <td>{{i.Duration}}</td>
            <td><a class="btn btn-warning" href="{% url 'detail' i.id %} " role="button">Book ticket</a></td>
            
        </tr>
 
        {%endfor%}

    </table>
</div>



{%endblock%}

flights/fly/templates/fly/ticket.html
{% extends 'base.html' %}

{% block content %}

Your Ticket has been Booked!

<h1>
{{Ticket.TicketNo}}
{{Ticket.Flight_Name}}
{{Ticket.Name}}
{{Ticket.From}}
{{Ticket.To}}
</h1>
{%endblock%}

flights/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>


<body>

    <nav>
        <div class="nav__logo"><img src="{% static 'img./logo.png.png'%}" width="50px" alt="" height="150px" ></div>
        <ul class="nav__links">
            <li class="link"><a href="{% url 'home'%}">Home</a></li>



            {% if request.user.username %}

            <li class="link"><a href="">{{request.user.username }}</a></li>
            <li class="link"><a href="{% url 'logout' %}">Logout</a></li>

            {%else%}

            <li class="link"><a href="{% url 'login' %}">Login</a></li>
            <li class="link"><a href="{% url 'register' %}">SignUp</a></li>

            {%endif%}
           
            <li class="link"><a href="{% url 'list' %}">Flights</a></li>






        </ul>
    </nav>

    <!--   ======================================================    -->


    {% block content %}

    {%endblock%}




<footer class="footer">
        <div class="section__container footer__container">
            <div class="footer__col">
                <h3>Fly Emirates</h3>
                <p>Where Excellence Takes Flights.with a astrong commitment to customer satisfication and a passion for air travel,Fly Emirates offers exceptional services and seamless journey.</p>
                <p>From Friendly smile to state-of-the-art aircraft,we connect the world,ensuring safe,comfortable,and unforgetable experiences.</p>
            </div>
            <div class="footer__col">
                <h4>INFORMATION</h4>
                <p>Home</p>
                <p>About</p>
                <p>Offers</p>
               
                <p>Destinations</p>
            </div>
            <div class="footer__col">
                <h4>CONTACT</h4>
                <p>Support</p>
                <p>Media</p>
                <p>Socials</p>
            </div>
        </div>
        <div class="section__container footer__bar">
            <p>This section contains the flights information</p>
            <div class="socials">
                <span><i class="ri-facebook-fill"></i></span>
                <span><i class="ri-twitter-fill"></i></span>
                <span><i class="ri-instagram-fill"></i></span>
                <span><i class="ri-youtube-fill"></i></span>
             
            </div>
        </div>
        
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



</body>
</html>

flights/templates/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>

    <h1>{{request.user.username}}</h1>

    <nav>
        <div class="nav__logo"><img src="{% static 'img/logo.png.png'%}" alt="image" width="50px" height="150px" ></div>
        <ul class="nav__links">
            <li class="link"><a href="{% url 'home'%}">Home</a></li>

            {% if request.user.username %}

            <li class="link"><a href="">{{request.user.username }}</a></li>
            <li class="link"><a href="{% url 'logout' %}">Logout</a></li>

            {%else%}

            <li class="link"><a href="{% url 'login' %}">Login</a></li>
            <li class="link"><a href="{% url 'register' %}">SignUp</a></li>

            {%endif%}

            <li class="link"><a href="{% url 'list' %}">Flights</a></li>


        </ul>
    </nav>
    <header class="section__container header__container">
        <h1 class="heading" style="text-align: center;">Find And Book</h1>
     <h1 class="heading" style="text-align: center;"> A Great Experience</h1>  
        <img src="{% static 'img/header.jpg' %}" alt="header">
    </header>
    <section class="section__container booking__container">
        <div class="booking__nav">
            <span><a style="text-decoration: none; color: black;" href="{% url 'category' 1 %}">Domestic</a></span>
            <span><a style="text-decoration: none; color: black; " href="{% url 'category' 2 %}" >International</a></span>
      
        </div>
        <form action={% url 'search'%}>
            <div class="form__group">
                <span><i class="ri-map-pin-line"></i></span>
                <div class="input__content">
                    <div class="input__group">
                        <input type="text" name="from">
                        <label for="">From</label>
                    </div>
                    <p>Where are you Going?</p>
                </div>
            </div>
            <div class="form__group">
                <span><i class="ri-user-3-line"></i></span>
                <div class="input__content">
                    <div class="input__group">
                        <input type="text" name="to">
                        <label for="">To</label>
                    </div>
                    <p>Add guest</p>
                </div>
            </div>
            <div class="form__group">
                <span><i class="ri-calendar-line"></i></span>
                <div class="input__content">
                    <div class="input__group">
                        <input type="date">
                        <label for=""></label>
                    </div>
                    <p>Add date</p>
                </div>
            </div>
            
            <button class="submit" style="background-color:#3d5cb8; width: 90%; margin: 10px;"><i class="ri-search-line"></i></button> 
        </form>
    </section>
    <section class="section__container plan__container">
        <p class="kagdi">TRAVEL SUPPORT</p>
        <h2 class="" style="text-align: center;">plan your travel with confidence</h2>
        <p class="description">
            find help with your booking and travel plans,and see what to expect along your journey.
        </p>
        <div class="plan__grid">
            <div class="plan__content">
                <span class="number">01</span>
                <h4>Travel Requriments for Dubai</h4>
                <p>stay informed and prepared for your trip to Dubai with essential travel requrements,ensuring a asmooth and hassle-free experience in this vibrant and captivating city.</p>

                <span class="number">02</span>
                <h4>Multi-risk Travel Insurance</h4>
                <p>comprehensive protection for your peace of mind,covering a range of potential travel risks and unexpected situations.
                </p>
                <span class="number">03</span>
                <h4>Travel Requriments by destinations</h4>
                <p>stay informed and prepared for your trip with ease,as we provide up-to-date information on travel requrements specific to your desired destinations.</p>

            </div>
           <!--Add images-->
            </div>
        </div>
    </section>

    <section class="memories">
        <div class="section__container memories__container">
            <div class="memories__header">
                <h2 class="section__header">
                    Travel to make mories all around the world
                </h2>
                <button class="view__all">View All</button>
            </div>
            <div class="memories__grid">
                <div class="memories__card">
                    <span><i class="ri-calendar-2-line"></i></span>
                    <h4>Book & Relax</h4>
                    <p>With "Book and relax" you can sit back,unwind,and enjoy the journey while we take care of everything else.</p>
                </div>
                <div class="memories__card">
                    <span><i class="ri-shield-check-line"></i></span>
                    <h4>Smart Checklist</h4>
                    <p>Introducing Smart Checklist with us, the innotiative solution revolutionizing the way you travel with our airlines.</p>
                </div>
                <div class="memories__card">
                    <span><i class="ri-bookmark-2-line"></i></span>
                    <h4>Save More</h4>
                    <p>From discounted ticket prices to exclusive promotions and deals,we priorities affordability without compromising on quality.</p>
                </div>
            </div>
        </div>


    </section>
    <section class="section__container lounge__container">
        <div class="lounge__image">
            <img src="{% static 'img/lounge-1.jpg'%}" alt="lounge">
            <img src="{% static 'img/lounge-2.jpg'%}" alt="lounge">
        </div>
        <div class="lounge__content">
            <h2 class="section__header">Unaccompanied Minor Lounge</h2>
            <div class="lounge__grid">
                <div class="lounge__details">
                    <h4>Experience Tranquility</h4>
                    <p>Serenity Haven offers a tranquil escape,featuring comfortable seating,calming ambiance,and attentive service.</p>
                </div>
                <div class="lounge__details">
                    <h4>Elevate Your Experience</h4>
                    <p>Designed for discerning travelrs,this exclusive lounge offers premium amenities,assistance,and private workspace.</p>
                </div>
                <div class="lounge__details">
                    <h4>A Welcoming space</h4>
                    <p>Serenity Haven offer a tranquil escape,featuring comfortable seating,calming ambiance,and attentive service.</p>
                </div>
                <div class="lounge__details">
                    <h4>A Culinary Delight</h4>
                    <p>Immerse yourself in a world of flavors,offering international cuisines,gourmet dishes,and carefully curated beverages.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="section__container travellers__container">
        <h2 class="section__header">Best Travellers of the month</h2>
        <div class="travellers__grid">
            <div class="travellers__card">
                <img src="{% static 'img/traveller-1.jpg'%}" alt="traveller">
                <div class="travellers__card__content">
                    <img src="{% static 'img/cl.jpg'%}" alt="client">
                    <h4>Elon Mask</h4>
                    <p>Dubai</p>
                </div>
            </div>
            <div class="travellers__card">
                <img src="{% static 'img/traveller-2.jpg'%}" alt="traveller">
                <div class="travellers__card__content">
                    <img src="{% static 'img/c2.jpg'%}" alt="client">
                    <h4>Bill Gates</h4>
                    <p>Paris</p>
                </div>
            </div>
            <div class="travellers__card">
                <img src="{% static 'img/traveller-3.jpg'%}" alt="traveller">
                <div class="travellers__card__content">
                    <img src="{% static 'img/c3.jpg'%}" alt="client">
                    <h4>Warren Buffett</h4>
                    <p>Singapore</p>
                </div>
            </div>
            <div class="travellers__card">
                <img src="{% static 'img/traveller-4.jpg'%}" alt="traveller">
                <div class="travellers__card__content">
                    <img src="{% static 'img/c4.jpg'%}" alt="client">
                    <h4>Sergey Brin</h4>
                    <p>Malaysia</p>
                </div>
            </div>
        </div>
    </section>

<section class="subscribe">
    <div class="section__container subscribe__container">
        <h2 class="section__header">Subscribe newsletter & get latest news</h2>
        <form class="subscribe__form">
            <input type="text" placeholder="Enter Your Email Here">
            <button class="btn">Subscribe</button>
        </form>
    </div>
</section>
<footer class="footer">
    <div class="section__container footer__container">
        <div class="footer__col">
            <h3>Fly Emirates</h3>
            <p>Where Excellence Takes Flights.with a astrong commitment to customer satisfication and a passion for air travel,Fly Emirates offers exceptional services and seamless journey.</p>
            <p>From Friendly smile to state-of-the-art aircraft,we connect the world,ensuring safe,comfortable,and unforgetable experiences.</p>
        </div>
        <div class="footer__col">
            <h4>INFORMATION</h4>
            <p>Home</p>
            <p>About</p>
            <p>Offers</p>
            <p>Destinations</p>
        </div>
        <div class="footer__col">
            <h4>CONTACT</h4>
            <p>Support</p>
            <p>Media</p>
            <p>Socials</p>
        </div>
    </div>
    <div class="section__container footer__bar">
        <p>This section contains the flights information</p>
        <div class="socials">
            <span><i class="ri-facebook-fill"></i></span>
            <span><i class="ri-twitter-fill"></i></span>
            <span><i class="ri-instagram-fill"></i></span>
            <span><i class="ri-youtube-fill"></i></span>
         
        </div>
    </div>
    
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>




</body>
</html>

flights/templates/login.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'login' %}" method="post">

    {% csrf_token %}


    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address</label>
      <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input name="password" type="password" class="form-control" id="exampleInputPassword1">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>


{%endblock%}

flights/templates/register.html
{% extends 'base.html' %}


{% block content %}

<form action="">

    {% csrf_token %}

{% for field in form %}

     {{field.label_tag}}<br>
     {{field}}<br>

{%endfor%}

<button class="button btn-primary" type="submit">Register</button>

</form>


{%endblock%}